### ISSUE TITLE
Dependencies gone

### ISSUE THREAD

**Issue by Name-Searcher** [Ewpratten/remoteplayers#1] opened 2021-03-22 16:32 UTC
I think Xaero's updated/removed his curse links so maven can no longer link to them 

> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find curse.maven:xaerominimap:3103772.

> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find curse.maven:xaeroworldmap:3103778.

putting the updated versions (or the closest version I could find) gives a java build error which I have no clue on how to fix
P.S. sorry if my formatting sucks idk how GitHub works

F:\Downloads\Minecraft 1.16.5\remoteplayers-master>gradlew build

> Configure project :
Fabric Loom: null
:setting up loom dependencies
:setting up mappings (yarn 1.16.4+build.6)

> Task :compileJava FAILED
2021-03-22 17:26:01,692 Execution worker for ':' WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
F:\Downloads\Minecraft 1.16.5\remoteplayers-master\src\main\java\ca\retrylife\mc\remoteplayers\mixins\WaypointsIngameRendererMixin.java:29: warning: Cannot inflect accessor target name
    @Accessor
    ^
Note: Writing refmap to F:\Downloads\Minecraft 1.16.5\remoteplayers-master\build\classes\java\main\remoteplayers-refmap.json
Note: Writing named:intermediary output TinyMappings to F:\Downloads\Minecraft 1.16.5\remoteplayers-master\build\loom-cache\mixin-map-1.16.4-1.16.4+build.6-v2.0.tiny
Note: Writing refmap to F:\Downloads\Minecraft 1.16.5\remoteplayers-master\build\classes\java\main\remoteplayers-refmap.json
Note: Writing named:intermediary output TinyMappings to F:\Downloads\Minecraft 1.16.5\remoteplayers-master\build\loom-cache\mixin-map-1.16.4-1.16.4+build.6-v2.0.tiny
F:\Downloads\Minecraft 1.16.5\remoteplayers-master\src\main\java\ca\retrylife\mc\remoteplayers\mixins\WaypointsIngameRendererMixin.java:25: error: cannot access class_310
        super(modMain, mc);
             ^
  class file for net.minecraft.class_310 not found
Note: F:\Downloads\Minecraft 1.16.5\remoteplayers-master\src\main\java\ca\retrylife\mc\remoteplayers\utils\HTTP.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by Ewpratten** [comment] 2021-03-26 12:40
Thank you for the info, I knew about this but didn't think to come update the project. The issue is actually that cursemaven changes their endpoints.

I'll make this fix in a few minutes.

**Comment by Ewpratten** [comment] 2021-03-26 13:01
This should be fixed. Please open another issue if you have any more problems.

**Closed** 2021-03-26 13:00 UTC
